version: "3.3"
services:
  nifi:
    container_name: bb-big-data-desafio-nifi
    image: apache/nifi:1.21.0
    user: root
    network_mode: bridge
    environment: 
      - COMPOSE_HTTP_TIMEOUT=240
    ports:
      - 8443:8443 
