version: "3.3"
services:
  nifi:
    container_name: bb-big-data-desafio-nifi
    image: apache/nifi:1.21.0
    user: root
    network_mode: bridge
    environment: 
      - COMPOSE_HTTP_TIMEOUT=240
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      #Minimo 12 caracteres
      - SINGLE_USER_CREDENTIALS_PASSWORD=bbbigdatadesafio
    ports:
      - 8443:8443 

#   zookeeper:
#     container_name: bb-big-data-desafio-zookeeper
#     image: confluentinc/cp-zookeeper:latest
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - 22181:2181
  
#   kafka:
#     container_name: bb-big-data-desafio-kafka
#     image: confluentinc/cp-kafka:latest
#     depends_on:
#       - zookeeper
#     ports:
#       - 29092:29092
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#   grafana:
#     container_name: bb-big-data-desafio-grafana
#     image: grafana/grafana:7.5.7
#     ports:
#       - 3000:3000
#     restart: unless-stopped
#     volumes:
#       - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#       - grafana-data:/var/lib/grafana
# volumes:
#   grafana-data:
